name: Build and Publish Maven Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn từ repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cài đặt JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build dự án Maven và đẩy artifact lên GitHub Packages
      - name: Build with Maven and Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}  # Sử dụng PAT từ secrets
        run: |
          mvn -B package --file pom.xml
          mvn -B deploy --file pom.xml -DskipTests